In [0]:
def test():
    print("test() for function")
    return
test()

test() for function


In [0]:

class demo:
    def test(self):
        print("test() for the class and method")
        return
obj=demo()
obj.test()

test() for the class and method


In [0]:
class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
    
p1=demo1()
print(p1.fact(5))


120


In [0]:

class demo2:
    def accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def display(s):
        print("p1=",s.p1)
        print("p2=",s.p2)
        
c1=demo2()
c1.accept(10,20)
c1.display()



p1= 10
p2= 20


In [0]:

class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2
    
c1=Demo2(10,20)
print(c1.add(100,200))



300


In [0]:
class Person():
    #Contructor
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False

In [0]:

# Derived Class
class Employee(Person):
    def isEmployee(self):
        return True
    
emp=Person("Ank")
print(emp.getName(),emp.isEmployee())

emp1=Employee("Sra")
print(emp1.getName(),emp1.isEmployee())



Ank False
Sra True


In [0]:
list=[1,2,3,4]
print(list)

[1, 2, 3, 4]


In [0]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [0]:

lst=[1,2,3,4]
array=np.array(lst)
array+10
print(array)

[1 2 3 4]


In [0]:

lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int64


In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [0]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [0]:


A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [0]:

import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:

np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [0]:

np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [0]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [25]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Column: ",a1[:,1])


Slicing Column:  [2 5]


In [26]:

a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Last Column: ",a1[:,2])

Slicing Last Column:  [3 6]


In [27]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min Value =",np.min(a1))
print("Max Value =",np.max(a1))
print("Mean Value =",np.mean(a1))
print("Median Value =",np.median(a1))

[4.21244746 3.43427112 3.48838479 6.59057099 4.56371055 5.22609823
 5.96639758 5.91039533 5.48803095 4.93007058]
Min Value = 3.434271120900519
Max Value = 6.590570989938831
Mean Value = 4.98103775810284
Median Value = 5.078084404283756
